# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.page_1)
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setLineWidth(0)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelMovie = QtWidgets.QLabel(self.frame_1)
        self.labelMovie.setMinimumSize(QtCore.QSize(800, 600))
        self.labelMovie.setMaximumSize(QtCore.QSize(800, 600))
        self.labelMovie.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.labelMovie.setLineWidth(0)
        self.labelMovie.setText("")
        self.labelMovie.setObjectName("labelMovie")
        self.verticalLayout_4.addWidget(self.labelMovie)
        self.frame = QtWidgets.QFrame(self.frame_1)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setStyleSheet("QProgressBar {    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border-style: none;\n"
"}\n"
"QProgressBar::chunk{    \n"
"    background-color: rgb(205, 37, 40);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_monitor = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_monitor.setGeometry(QtCore.QRect(40, 50, 60, 60))
        self.pushButton_monitor.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_monitor.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_monitor.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    border-image: url(:/icons/monitor_off.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 0px solid;\n"
"       border-image: url(:/icons/monitor_on.png);\n"
"}\n"
"QPushButton:focus {\n"
"    border: 0px solid;\n"
"       border-image: url(:/icons/monitor_on.png);\n"
"}\n"
"")
        self.pushButton_monitor.setText("")
        self.pushButton_monitor.setObjectName("pushButton_monitor")
        self.pushButton_docker = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_docker.setGeometry(QtCore.QRect(40, 160, 60, 60))
        self.pushButton_docker.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_docker.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_docker.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    border-image: url(:/icons/docker_off.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 0px solid;\n"
"   border-image: url(:/icons/docker_on.png);\n"
"}\n"
"QPushButton:focus {\n"
"    border: 0px solid;\n"
"   border-image: url(:/icons/docker_on.png);\n"
"}\n"
"")
        self.pushButton_docker.setText("")
        self.pushButton_docker.setObjectName("pushButton_docker")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mouse_frame_1 = QtWidgets.QFrame(self.frame_5)
        self.mouse_frame_1.setMinimumSize(QtCore.QSize(0, 40))
        self.mouse_frame_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mouse_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mouse_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mouse_frame_1.setLineWidth(0)
        self.mouse_frame_1.setObjectName("mouse_frame_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mouse_frame_1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(602, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.frame_14 = QtWidgets.QFrame(self.mouse_frame_1)
        self.frame_14.setMinimumSize(QtCore.QSize(120, 40))
        self.frame_14.setMaximumSize(QtCore.QSize(120, 40))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_minimize_1 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_minimize_1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_minimize_1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_minimize_1.setStyleSheet("QPushButton {\n"
"    border-image: url(:/icons/minimize.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border-image: url(:/icons/minimize_on.png);\n"
"}\n"
"")
        self.pushButton_minimize_1.setText("")
        self.pushButton_minimize_1.setObjectName("pushButton_minimize_1")
        self.horizontalLayout_10.addWidget(self.pushButton_minimize_1)
        self.pushButton_maximize_1 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_maximize_1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_maximize_1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_maximize_1.setStyleSheet("QPushButton {\n"
"    border-image: url(:/icons/maximize.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border-image: url(:/icons/maximize_on.png);\n"
"}\n"
"\n"
"")
        self.pushButton_maximize_1.setText("")
        self.pushButton_maximize_1.setObjectName("pushButton_maximize_1")
        self.horizontalLayout_10.addWidget(self.pushButton_maximize_1)
        self.pushButtonClose_1 = QtWidgets.QPushButton(self.frame_14)
        self.pushButtonClose_1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonClose_1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonClose_1.setStyleSheet("QPushButton {\n"
"    border-image: url(:/icons/close.png);\n"
"}\n"
"QPushButton:hover {\n"
"    border-image: url(:/icons/close_on.png);\n"
"}")
        self.pushButtonClose_1.setText("")
        self.pushButtonClose_1.setObjectName("pushButtonClose_1")
        self.horizontalLayout_10.addWidget(self.pushButtonClose_1)
        self.horizontalLayout_3.addWidget(self.frame_14)
        self.verticalLayout_3.addWidget(self.mouse_frame_1)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidgetMenu = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidgetMenu.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.stackedWidgetMenu.setLineWidth(0)
        self.stackedWidgetMenu.setObjectName("stackedWidgetMenu")
        self.pageMenu = QtWidgets.QWidget()
        self.pageMenu.setObjectName("pageMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageMenu)
        self.verticalLayout_5.setContentsMargins(20, 9, 20, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.pageMenu)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.pageMenu)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_3.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(500, 20, 311, 211))
        self.frame_9.setStyleSheet("QFrame{\n"
"    border-radius: 6px;\n"
"    \n"
"    \n"
"    background-color: rgb(184, 184, 184);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidgetTraffic = QtWidgets.QTableWidget(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetTraffic.sizePolicy().hasHeightForWidth())
        self.tableWidgetTraffic.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tableWidgetTraffic.setPalette(palette)
        self.tableWidgetTraffic.setAcceptDrops(True)
        self.tableWidgetTraffic.setStyleSheet("QFrame {\n"
"    border: 0px solid;\n"
"    border-radius: 0px;\n"
"    color: rgb(253, 253, 253);\n"
"    background-color: rgb(36, 36, 36);\n"
"}\n"
"")
        self.tableWidgetTraffic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetTraffic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetTraffic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetTraffic.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetTraffic.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidgetTraffic.setDragEnabled(True)
        self.tableWidgetTraffic.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidgetTraffic.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetTraffic.setShowGrid(True)
        self.tableWidgetTraffic.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetTraffic.setRowCount(16)
        self.tableWidgetTraffic.setColumnCount(3)
        self.tableWidgetTraffic.setObjectName("tableWidgetTraffic")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTraffic.setItem(15, 2, item)
        self.tableWidgetTraffic.horizontalHeader().setVisible(False)
        self.tableWidgetTraffic.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetTraffic.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidgetTraffic.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetTraffic.verticalHeader().setVisible(False)
        self.tableWidgetTraffic.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetTraffic.verticalHeader().setHighlightSections(False)
        self.tableWidgetTraffic.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_6.addWidget(self.tableWidgetTraffic)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_infos_3 = QtWidgets.QFrame(self.pageMenu)
        self.frame_infos_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_infos_3.setStyleSheet("QFrame {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.frame_infos_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infos_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infos_3.setLineWidth(1)
        self.frame_infos_3.setObjectName("frame_infos_3")
        self.frameMemoColor = QtWidgets.QFrame(self.frame_infos_3)
        self.frameMemoColor.setGeometry(QtCore.QRect(290, 20, 250, 250))
        self.frameMemoColor.setMinimumSize(QtCore.QSize(250, 250))
        self.frameMemoColor.setMaximumSize(QtCore.QSize(250, 250))
        self.frameMemoColor.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(205, 37, 40);\n"
"    border-radius: 125px;\n"
"}\n"
"")
        self.frameMemoColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMemoColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMemoColor.setObjectName("frameMemoColor")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frameMemoColor)
        self.verticalLayout_12.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.labelMemo = QtWidgets.QLabel(self.frameMemoColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.labelMemo.setFont(font)
        self.labelMemo.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.labelMemo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemo.setObjectName("labelMemo")
        self.verticalLayout_12.addWidget(self.labelMemo)
        self.labelMemoPercent = QtWidgets.QLabel(self.frameMemoColor)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelMemoPercent.setFont(font)
        self.labelMemoPercent.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelMemoPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemoPercent.setObjectName("labelMemoPercent")
        self.verticalLayout_12.addWidget(self.labelMemoPercent)
        self.labelMemoTotal = QtWidgets.QLabel(self.frameMemoColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.labelMemoTotal.setFont(font)
        self.labelMemoTotal.setStyleSheet("border: none;\n"
" color: rgb(255, 255, 255);")
        self.labelMemoTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemoTotal.setObjectName("labelMemoTotal")
        self.verticalLayout_12.addWidget(self.labelMemoTotal)
        self.labelMemoFree = QtWidgets.QLabel(self.frameMemoColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelMemoFree.setFont(font)
        self.labelMemoFree.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.labelMemoFree.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemoFree.setObjectName("labelMemoFree")
        self.verticalLayout_12.addWidget(self.labelMemoFree)
        self.frameGpuColor = QtWidgets.QFrame(self.frame_infos_3)
        self.frameGpuColor.setGeometry(QtCore.QRect(560, 20, 250, 250))
        self.frameGpuColor.setMinimumSize(QtCore.QSize(250, 250))
        self.frameGpuColor.setMaximumSize(QtCore.QSize(250, 250))
        self.frameGpuColor.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(205, 0, 0);\n"
"    border-radius: 125px;\n"
"}\n"
"")
        self.frameGpuColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGpuColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGpuColor.setObjectName("frameGpuColor")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frameGpuColor)
        self.verticalLayout_13.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelGpu = QtWidgets.QLabel(self.frameGpuColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.labelGpu.setFont(font)
        self.labelGpu.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.labelGpu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGpu.setObjectName("labelGpu")
        self.verticalLayout_13.addWidget(self.labelGpu)
        self.labelGpuPercent = QtWidgets.QLabel(self.frameGpuColor)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelGpuPercent.setFont(font)
        self.labelGpuPercent.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelGpuPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGpuPercent.setObjectName("labelGpuPercent")
        self.verticalLayout_13.addWidget(self.labelGpuPercent)
        self.labelGpuTotal = QtWidgets.QLabel(self.frameGpuColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.labelGpuTotal.setFont(font)
        self.labelGpuTotal.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.labelGpuTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGpuTotal.setObjectName("labelGpuTotal")
        self.verticalLayout_13.addWidget(self.labelGpuTotal)
        self.labelGpuFree = QtWidgets.QLabel(self.frameGpuColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelGpuFree.setFont(font)
        self.labelGpuFree.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.labelGpuFree.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGpuFree.setObjectName("labelGpuFree")
        self.verticalLayout_13.addWidget(self.labelGpuFree)
        self.frameCpuColor = QtWidgets.QFrame(self.frame_infos_3)
        self.frameCpuColor.setGeometry(QtCore.QRect(20, 20, 250, 250))
        self.frameCpuColor.setMinimumSize(QtCore.QSize(250, 250))
        self.frameCpuColor.setMaximumSize(QtCore.QSize(250, 250))
        self.frameCpuColor.setStyleSheet("QFrame{border: 5px solid rgb(255, 255, 255);border-radius: 125px;}\n"
"")
        self.frameCpuColor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCpuColor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCpuColor.setObjectName("frameCpuColor")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frameCpuColor)
        self.verticalLayout_14.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.labelCpu = QtWidgets.QLabel(self.frameCpuColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.labelCpu.setFont(font)
        self.labelCpu.setStyleSheet("border: none;\n"
"color: rgba(255, 255, 255,255);")
        self.labelCpu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpu.setObjectName("labelCpu")
        self.verticalLayout_14.addWidget(self.labelCpu)
        self.labelCpuPercent = QtWidgets.QLabel(self.frameCpuColor)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelCpuPercent.setFont(font)
        self.labelCpuPercent.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelCpuPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpuPercent.setObjectName("labelCpuPercent")
        self.verticalLayout_14.addWidget(self.labelCpuPercent)
        self.labelCpuCore = QtWidgets.QLabel(self.frameCpuColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.labelCpuCore.setFont(font)
        self.labelCpuCore.setStyleSheet("border: none;\n"
" color: rgb(255, 255, 255);")
        self.labelCpuCore.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpuCore.setObjectName("labelCpuCore")
        self.verticalLayout_14.addWidget(self.labelCpuCore)
        self.labelCpuTemp = QtWidgets.QLabel(self.frameCpuColor)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelCpuTemp.setFont(font)
        self.labelCpuTemp.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.labelCpuTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpuTemp.setObjectName("labelCpuTemp")
        self.verticalLayout_14.addWidget(self.labelCpuTemp)
        self.verticalLayout_5.addWidget(self.frame_infos_3)
        self.stackedWidgetMenu.addWidget(self.pageMenu)
        self.pageDocker = QtWidgets.QWidget()
        self.pageDocker.setObjectName("pageDocker")
        self.stackedWidgetMenu.addWidget(self.pageDocker)
        self.horizontalLayout_5.addWidget(self.stackedWidgetMenu)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.Garbage = QtWidgets.QWidget()
        self.Garbage.setObjectName("Garbage")
        self.frame_11 = QtWidgets.QFrame(self.Garbage)
        self.frame_11.setGeometry(QtCore.QRect(10, 10, 991, 761))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 120, 40))
        self.frame_12.setMinimumSize(QtCore.QSize(120, 40))
        self.frame_12.setMaximumSize(QtCore.QSize(120, 40))
        self.frame_12.setStyleSheet("background-color: rgb(149, 108, 51);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setLineWidth(0)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_11.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_11.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_11.setStyleSheet("border-image: url(:/icons/minimize.png);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_8.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_12.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_12.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_12.setStyleSheet("border-image: url(:/icons/maximize.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_8.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_13.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_13.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_13.setStyleSheet("border-image: url(:/icons/close.png);")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.frame_infos_2 = QtWidgets.QFrame(self.frame_11)
        self.frame_infos_2.setGeometry(QtCore.QRect(670, 10, 311, 341))
        self.frame_infos_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infos_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infos_2.setObjectName("frame_infos_2")
        self.frameCpu_2 = QtWidgets.QFrame(self.frame_infos_2)
        self.frameCpu_2.setGeometry(QtCore.QRect(70, 20, 250, 250))
        self.frameCpu_2.setMinimumSize(QtCore.QSize(250, 250))
        self.frameCpu_2.setMaximumSize(QtCore.QSize(250, 250))
        self.frameCpu_2.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(115, 241, 255);\n"
"    border-radius: 125px;\n"
"}\n"
"")
        self.frameCpu_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCpu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCpu_2.setObjectName("frameCpu_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameCpu_2)
        self.verticalLayout_7.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frameCpu_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.labelCpuName_2 = QtWidgets.QLabel(self.frameCpu_2)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(8)
        self.labelCpuName_2.setFont(font)
        self.labelCpuName_2.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.labelCpuName_2.setText("")
        self.labelCpuName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpuName_2.setObjectName("labelCpuName_2")
        self.verticalLayout_7.addWidget(self.labelCpuName_2)
        self.labelCpuPer_2 = QtWidgets.QLabel(self.frameCpu_2)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelCpuPer_2.setFont(font)
        self.labelCpuPer_2.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelCpuPer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpuPer_2.setObjectName("labelCpuPer_2")
        self.verticalLayout_7.addWidget(self.labelCpuPer_2)
        self.labelCpuTemp_2 = QtWidgets.QLabel(self.frameCpu_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelCpuTemp_2.setFont(font)
        self.labelCpuTemp_2.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.labelCpuTemp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCpuTemp_2.setObjectName("labelCpuTemp_2")
        self.verticalLayout_7.addWidget(self.labelCpuTemp_2)
        self.frameMemory_2 = QtWidgets.QFrame(self.frame_infos_2)
        self.frameMemory_2.setGeometry(QtCore.QRect(320, 20, 250, 250))
        self.frameMemory_2.setMinimumSize(QtCore.QSize(250, 250))
        self.frameMemory_2.setMaximumSize(QtCore.QSize(250, 250))
        self.frameMemory_2.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(115, 241, 255);\n"
"    border-radius: 125px;\n"
"}\n"
"")
        self.frameMemory_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMemory_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMemory_2.setObjectName("frameMemory_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameMemory_2)
        self.verticalLayout_9.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frameMemory_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.labelMemPer_2 = QtWidgets.QLabel(self.frameMemory_2)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelMemPer_2.setFont(font)
        self.labelMemPer_2.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelMemPer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemPer_2.setObjectName("labelMemPer_2")
        self.verticalLayout_9.addWidget(self.labelMemPer_2)
        self.labelMemTotal_2 = QtWidgets.QLabel(self.frameMemory_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.labelMemTotal_2.setFont(font)
        self.labelMemTotal_2.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.labelMemTotal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemTotal_2.setObjectName("labelMemTotal_2")
        self.verticalLayout_9.addWidget(self.labelMemTotal_2)
        self.labelMemUsed_2 = QtWidgets.QLabel(self.frameMemory_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelMemUsed_2.setFont(font)
        self.labelMemUsed_2.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.labelMemUsed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemUsed_2.setObjectName("labelMemUsed_2")
        self.verticalLayout_9.addWidget(self.labelMemUsed_2)
        self.frameMemory_3 = QtWidgets.QFrame(self.frame_infos_2)
        self.frameMemory_3.setGeometry(QtCore.QRect(480, 180, 250, 250))
        self.frameMemory_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frameMemory_3.setMaximumSize(QtCore.QSize(250, 250))
        self.frameMemory_3.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(115, 241, 255);\n"
"    border-radius: 125px;\n"
"}\n"
"")
        self.frameMemory_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMemory_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMemory_3.setObjectName("frameMemory_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameMemory_3)
        self.verticalLayout_10.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.frameMemory_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.labelMemPer_3 = QtWidgets.QLabel(self.frameMemory_3)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelMemPer_3.setFont(font)
        self.labelMemPer_3.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelMemPer_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemPer_3.setObjectName("labelMemPer_3")
        self.verticalLayout_10.addWidget(self.labelMemPer_3)
        self.labelMemTotal_3 = QtWidgets.QLabel(self.frameMemory_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.labelMemTotal_3.setFont(font)
        self.labelMemTotal_3.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.labelMemTotal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemTotal_3.setObjectName("labelMemTotal_3")
        self.verticalLayout_10.addWidget(self.labelMemTotal_3)
        self.labelMemUsed_3 = QtWidgets.QLabel(self.frameMemory_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelMemUsed_3.setFont(font)
        self.labelMemUsed_3.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.labelMemUsed_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemUsed_3.setObjectName("labelMemUsed_3")
        self.verticalLayout_10.addWidget(self.labelMemUsed_3)
        self.frameMemory_4 = QtWidgets.QFrame(self.frame_infos_2)
        self.frameMemory_4.setGeometry(QtCore.QRect(230, 190, 250, 250))
        self.frameMemory_4.setMinimumSize(QtCore.QSize(250, 250))
        self.frameMemory_4.setMaximumSize(QtCore.QSize(250, 250))
        self.frameMemory_4.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(115, 241, 255);\n"
"    border-radius: 125px;\n"
"}\n"
"")
        self.frameMemory_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMemory_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMemory_4.setObjectName("frameMemory_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frameMemory_4)
        self.verticalLayout_11.setContentsMargins(30, 50, 30, 50)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.frameMemory_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.labelMemPer_4 = QtWidgets.QLabel(self.frameMemory_4)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(50)
        self.labelMemPer_4.setFont(font)
        self.labelMemPer_4.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.labelMemPer_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemPer_4.setObjectName("labelMemPer_4")
        self.verticalLayout_11.addWidget(self.labelMemPer_4)
        self.labelMemTotal_4 = QtWidgets.QLabel(self.frameMemory_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.labelMemTotal_4.setFont(font)
        self.labelMemTotal_4.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.labelMemTotal_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemTotal_4.setObjectName("labelMemTotal_4")
        self.verticalLayout_11.addWidget(self.labelMemTotal_4)
        self.labelMemUsed_4 = QtWidgets.QLabel(self.frameMemory_4)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.labelMemUsed_4.setFont(font)
        self.labelMemUsed_4.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.labelMemUsed_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMemUsed_4.setObjectName("labelMemUsed_4")
        self.verticalLayout_11.addWidget(self.labelMemUsed_4)
        self.frame_8 = QtWidgets.QFrame(self.frame_11)
        self.frame_8.setGeometry(QtCore.QRect(120, 100, 411, 321))
        self.frame_8.setStyleSheet("gridline-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.line = QtWidgets.QFrame(self.frame_8)
        self.line.setGeometry(QtCore.QRect(60, 120, 118, 16))
        self.line.setStyleSheet("background-color: rgb(255, 26, 26);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget.addWidget(self.Garbage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidgetTraffic.setSortingEnabled(False)
        item = self.tableWidgetTraffic.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetTraffic.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidgetTraffic.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidgetTraffic.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.tableWidgetTraffic.isSortingEnabled()
        self.tableWidgetTraffic.setSortingEnabled(False)
        item = self.tableWidgetTraffic.item(0, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(0, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(0, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(1, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(1, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(1, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(2, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(2, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(2, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(3, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(3, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(3, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(4, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(4, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(4, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(5, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(5, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(5, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(6, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(6, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(6, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(7, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(7, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(7, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(8, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(8, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(8, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(9, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(9, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(9, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(10, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(10, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(10, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(11, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(11, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(11, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(12, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(12, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(12, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(13, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(13, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(13, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(14, 0)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(14, 1)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(14, 2)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidgetTraffic.item(15, 0)
        item.setText(_translate("MainWindow", "  "))
        item = self.tableWidgetTraffic.item(15, 2)
        item.setText(_translate("MainWindow", "  "))
        self.tableWidgetTraffic.setSortingEnabled(__sortingEnabled)
        self.labelMemo.setText(_translate("MainWindow", "RAM USAGE"))
        self.labelMemoPercent.setText(_translate("MainWindow", "0%"))
        self.labelMemoTotal.setText(_translate("MainWindow", "Total: 0Gb"))
        self.labelMemoFree.setText(_translate("MainWindow", "Used: 0Gb"))
        self.labelGpu.setText(_translate("MainWindow", "GPU USAGE"))
        self.labelGpuPercent.setText(_translate("MainWindow", "0%"))
        self.labelGpuTotal.setText(_translate("MainWindow", "Total: 0Gb"))
        self.labelGpuFree.setText(_translate("MainWindow", "Used: 0Gb"))
        self.labelCpu.setText(_translate("MainWindow", "CPU USAGE"))
        self.labelCpuPercent.setText(_translate("MainWindow", "0%"))
        self.labelCpuCore.setText(_translate("MainWindow", "Cores:"))
        self.labelCpuTemp.setText(_translate("MainWindow", "Temp: "))
        self.label_2.setText(_translate("MainWindow", "CPU USAGE"))
        self.labelCpuPer_2.setText(_translate("MainWindow", "0%"))
        self.labelCpuTemp_2.setText(_translate("MainWindow", "Temp: 0Cº"))
        self.label_10.setText(_translate("MainWindow", "RAM USAGE"))
        self.labelMemPer_2.setText(_translate("MainWindow", "0%"))
        self.labelMemTotal_2.setText(_translate("MainWindow", "Total: 0Gb"))
        self.labelMemUsed_2.setText(_translate("MainWindow", "Used: 0Gb"))
        self.label_11.setText(_translate("MainWindow", "RAM USAGE"))
        self.labelMemPer_3.setText(_translate("MainWindow", "0%"))
        self.labelMemTotal_3.setText(_translate("MainWindow", "Total: 0Gb"))
        self.labelMemUsed_3.setText(_translate("MainWindow", "Used: 0Gb"))
        self.label_12.setText(_translate("MainWindow", "RAM USAGE"))
        self.labelMemPer_4.setText(_translate("MainWindow", "0%"))
        self.labelMemTotal_4.setText(_translate("MainWindow", "Total: 0Gb"))
        self.labelMemUsed_4.setText(_translate("MainWindow", "Used: 0Gb"))


import images_rc
